In [1]:
import numpy as np
import pickle
import pandas as pd
import os
import sklearn
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
import csv

BASEPATH_EMBEDDINGS = "resources/word_embeddings/"
BASEPATH_XANEW = "resources\XANEW_lexicon"
WIKIPEDIA2VEC_FILENAME = "enwiki_20180420_300d.txt"
EMBEDS2012 = "resources/embeds2012_labeled.csv"

In [15]:
df_embeds2012 = pd.read_csv(EMBEDS2012)
df_embeds2012 = df_embeds2012[df_embeds2012['word'] != 'nan']

xanew_csv_location = os.path.join(BASEPATH_XANEW, 'Ratings_Warriner_et_al.csv')
df_xanew = pd.read_csv(xanew_csv_location, index_col=0)
df_xanew = df_xanew[['Word','V.Mean.Sum', 'A.Mean.Sum', 'D.Mean.Sum']]
df_xanew.columns=['word', 'valence_gold', 'arousal', 'dominance']
df_xanew = df_xanew[['valence_gold', 'word']]
df_xanew = df_xanew[0:]

In [39]:

vocab2012 = pickle.load(open("resources/word_embeddings/2012-vocab.pkl", "rb"))
embeds2012 = np.load(open("resources/word_embeddings/2012-w.npy",  "rb"))

nonAlignedembeds2012df = pd.DataFrame(np.column_stack((vocab2012, embeds2012)))
nonAlignedembeds2012df.rename(columns={nonAlignedembeds2012df.columns[0]: 'word'}, inplace=True)
nonAlignedembeds2012df.iloc[:, 1:] = nonAlignedembeds2012df.iloc[:, 1:].astype(float)
nonAlignedembeds2012df


fullA = pickle.load(open("resources/fullAvalList.pkl", "rb"))

In [34]:
set(embeds2012df["word"]) == set(nonAlignedembeds2012df["word"])

True

In [32]:
#FULLY_AVAILABLE_FILENAME = "histWord_fullAvail_1800.pickle"

#with open(os.path.join(BASEPATH_EMBEDDINGS, FULLY_AVAILABLE_FILENAME), 'rb') as f:
#    data_fully_available = pickle.load(f)
#vocab_fully_available = set(data_fully_available['1990']["word"]) #doesn't actually matter which year as long as it is present

#len(set(df_embeds2012['word']).intersection(vocab_fully_available))
df_embeds2012 = pd.read_csv(EMBEDS2012)


vocab2012 = pickle.load(open("resources/word_embeddings/aligned_2012-vocab.pkl", "rb"))
embeds2012 = np.load(open("resources/word_embeddings/aligned_2012-w.npy",  "rb"))

embeds2012df = pd.DataFrame(np.column_stack((vocab2012, embeds2012)))
embeds2012df.rename(columns={embeds2012df.columns[0]: 'word'}, inplace=True)
embeds2012df.iloc[:, 1:] = embeds2012df.iloc[:, 1:].astype(float)
embeds2012df[embeds2012df['word'] == "nan"]

,word,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,300
4975,nan,0.021269,0.146749,0.043977,-0.068561,-0.027912,-0.077673,0.052477,0.135661,0.048221,...,0.060285,0.033281,0.052869,-0.009865,0.114497,0.061144,-0.094331,-0.056798,-0.05168,-0.008077
15902,nan,0.181037,0.103486,-0.043091,0.035791,-0.118491,-0.066636,-0.068915,0.075213,-0.009915,...,-0.039242,-0.015196,0.008879,0.065153,0.067354,-0.053246,-0.16708,-0.014978,-0.052037,0.027954

In [17]:
(set(embeds2012df['word'])^(set(df_embeds2012['word'])))

{nan, 'nan'}

In [18]:
len(embeds2012df['word'])

21193

In [19]:
len(df_embeds2012['word'])

21193

In [22]:
df_embeds2012[df_embeds2012['word'] == np.nan]

Empty DataFrame
Columns: [word, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 302 columns]

In [41]:
columns = ['word'] + [f'{i}' for i in range(1, 301)]  # Assuming 300 columns
# Initialize an empty list to store the rows
rows = []
valid_words = set(embeds2012df.iloc[:, 0])#.union(set(df_xanew['word']))

with open(os.path.join(BASEPATH_EMBEDDINGS, WIKIPEDIA2VEC_FILENAME), 'r', encoding='utf-8') as file:
    for i, line in enumerate(file):
        if i == 0:
            continue

        values = line.strip().split()

        if values[0] in fullA:
            rows.append(values)

# Create the DataFrame
df_wikipedia2vec = pd.DataFrame(rows, columns=columns)

#order to same order as 2012 embeddings
#order_dict = {word: index for index, word in enumerate(list(df_embeds2012['word']))}
#df_wikipedia2vec['index_position'] = df_wikipedia2vec['word'].map(order_dict)
#df_wikipedia2vec = df_wikipedia2vec.sort_values('index_position')
#df_wikipedia2vec = df_wikipedia2vec.drop('index_position', axis=1)

rows, columns, valid_words = [], [], []
file.close()

In [43]:
df_wikipedia2vec

,word,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,300
0,the,-0.2430,-0.0432,-0.0333,0.1043,0.0213,-0.2068,-0.1589,0.0016,0.0184,...,-0.0228,0.2291,0.0403,-0.0804,-0.0724,0.1248,0.0292,-0.0283,-0.0504,-0.3401
1,in,-0.3310,-0.0557,0.1030,-0.0261,0.0266,-0.1006,0.0147,0.0280,0.0920,...,0.1188,0.1541,-0.0471,-0.1463,-0.2878,0.1590,-0.0207,-0.0287,0.1348,-0.0836
2,of,-0.2399,-0.2129,-0.0030,-0.1651,0.1162,-0.1942,-0.1294,0.0807,0.1837,...,0.0780,0.0933,0.0372,-0.0160,-0.1739,0.2253,0.1004,0.1116,-0.0116,-0.2252
3,a,-0.1686,0.0595,0.1338,-0.1783,-0.0722,-0.1563,-0.0439,-0.0922,0.0136,...,0.1143,0.2627,0.4164,-0.2029,-0.2053,-0.0663,-0.0264,0.1299,-0.1982,-0.2096
4,and,-0.2284,0.0096,0.0138,-0.0305,-0.1337,-0.0582,-0.0050,0.0831,0.0274,...,0.1160,0.0941,0.0084,-0.1385,-0.0931,0.1550,0.0106,-0.0505,0.0286,-0.2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12742,circumstanced,-0.0853,-0.0482,-0.0761,-0.0415,-0.3751,-0.0397,-0.3446,-0.0348,0.0389,...,0.0092,0.2309,0.1993,0.0981,-0.2675,-0.0519,-0.0344,-0.0261,0.0821,0.1632
12743,frighted,0.0132,0.1800,-0.3580,-0.0513,-0.0614,-0.2422,-0.1282,0.0394,-0.0975,...,0.2024,-0.1384,0.1582,-0.2041,-0.0984,0.1037,0.0787,-0.0172,0.3062,-0.1239
12744,intrusted,-0.0070,0.1454,-0.0712,-0.0696,-0.1233,0.0123,-0.0536,-0.1617,-0.0612,...,0.4433,0.0088,0.2269,-0.2811,0.0513,0.1473,-0.0497,0.1263,0.1707,0.1029
12745,heareth,0.0830,0.3277,0.0354,-0.0079,0.0100,0.0666,-0.0793,0.0208,0.0741,...,0.1926,-0.1673,0.1038,-0.2073,0.1711,0.1684,-0.0022,-0.0018,0.0041,0.1735
12746,hereinbefore,-0.1203,0.2363,-0.2136,0.0352,0.0162,-0.1961,-0.0368,0.0450,-0.0591,...,0.1783,-0.1229,0.2585,-0.0196,-0.0180,0.0138,-0.0420,0.2239,0.0017,0.0262

In [44]:
with open(os.path.join(BASEPATH_EMBEDDINGS, "12012-vocab.pkl"), 'wb') as f:
    pickle.dump(list(df_embeds2012["word"]), f)
    
with open(os.path.join(BASEPATH_EMBEDDINGS, "12012-w.npy"), 'wb') as f:
    np.save(f, df_embeds2012.iloc[:, 1:301])
    
with open(os.path.join(BASEPATH_EMBEDDINGS, "10000-vocab.pkl"), 'wb') as f:
    pickle.dump(list(df_wikipedia2vec["word"]), f)
    
with open(os.path.join(BASEPATH_EMBEDDINGS, "10000-w.npy"), 'wb') as f:
    np.save(f, df_wikipedia2vec.iloc[:, 1:].astype(float))

In [45]:
from vecanalysis import alignment
from representations.representation_factory import create_representation
from ioutils import write_pickle, words_above_count, mkdir

def align_years(years, rep_type, in_dir, out_dir, words, **rep_args):
    first_iter = True
    base_embed = None
    for year in years:
        print("Loading year:", year)
        year_embed = create_representation(rep_type, in_dir + str(year), **rep_args)
        year_words = words[str(year)]
        year_embed.get_subembed(year_words)
        print("Aligning year:", year)
        if first_iter:
            aligned_embed = year_embed
            first_iter = False
        else:
            aligned_embed = alignment.smart_procrustes_align(base_embed, year_embed)
        base_embed = aligned_embed
        print("Writing year:", year)
        foutname = out_dir + str(year)
        np.save(foutname + "-w.npy",aligned_embed.m)
        write_pickle(aligned_embed.iw, foutname + "-vocab.pkl")
        
align_years([12012, 10000], 'word2vec', BASEPATH_EMBEDDINGS, BASEPATH_EMBEDDINGS + "aligned_", {'12012': list(df_embeds2012['word']), '10000': list(df_wikipedia2vec['word'])})

Loading year: 12012
Aligning year: 12012
Writing year: 12012
Loading year: 10000
Aligning year: 10000
Writing year: 10000

In [46]:
l = np.load(open("resources/word_embeddings/aligned_10000-w.npy",  "rb"))
len(l)

12747

In [47]:
aligned_wikipedia_embeds = np.load(open("resources/word_embeddings/aligned_10000-w.npy",  "rb"))
with open(os.path.join("resources/word_embeddings/aligned_10000-vocab.pkl"), 'rb') as f:
    aligned_wikipedia_vocab = pickle.load(f)

df_aligned_wikpedia2vec = pd.DataFrame(aligned_wikipedia_embeds)
df_aligned_wikpedia2vec["word"] = aligned_wikipedia_vocab

In [48]:
with open("regression_model_trainset.pkl", 'rb') as f:
    model = pickle.load(f)
with open("testset_words.pkl", 'rb') as f:
    testwords = pickle.load(f)

df_aligned_wikpedia2vec = df_aligned_wikpedia2vec[df_aligned_wikpedia2vec['word'].isin(testwords)]
df_aligned_wikpedia2vec['valence_pred'] = model.predict(df_aligned_wikpedia2vec.iloc[:, :-1])

df_aligned_wikpedia2vec = pd.merge(df_aligned_wikpedia2vec, df_xanew, on='word', how='inner')

In [49]:
msre = sklearn.metrics.mean_squared_error(df_aligned_wikpedia2vec['valence_gold'], df_aligned_wikpedia2vec['valence_pred'])
print("MSRE of model: " + str(msre))
msreDummy = sklearn.metrics.mean_squared_error(df_aligned_wikpedia2vec['valence_gold'], [5.0] * len(df_aligned_wikpedia2vec['valence_pred']))
print("MSRE of dummy model: " + str(msreDummy))

MSRE of model: 0.7947802456801157
MSRE of dummy model: 1.7773629422718809